---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
  - package-ecosystem: npm
    open-pull-requests-limit: 1
    directory: /
    schedule:
      interval: daily
    reviewers:
      - drugscom/ops
